name: palace_example
description: A simple collection of examples form the palace package

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  palace:
    path: ../
dev_dependencies:
  pedantic: ^1.9.0
