name: palace_logger
description: palace_logger helper for palace framework to make handling logs easier
version: 1.0.0
homepage: https://github.com/maxzod/palace_core

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
